const freeze = (items) => Object.freeze(items);

export const MEAL_PLAN_FOOD_CURATION_GROUPS = Object.freeze({
  uncommonReferenceFoods: freeze([
    "Bánh bích cốt",
    "Bánh trứng nhện",
    "Bột cóc",
    "Củ cái (Yam winged)",
    "Củ niễng",
    "Củ súng khô",
    "Dâu gia",
    "Gioi",
    "Hạt đen",
    "Khoai nước",
    "Khoai riềng",
    "Lạc chao dầu",
    "Mắc coọc",
    "Mắc coọc nước đường",
    "Muỗm, quéo",
    "Nhút (muối từ mít non, ngọn đậu xanh non...)",
    "Nụ mướp",
    "Quả cọ tươi",
    "Quả dọc",
    "Quả đại hải tươi",
    "Rau sắng (chùa Hương)",
    "Rau tàu bay",
    "Sữa mẹ (sữa người)",
    "Đậu trứng cuốc",
  ]),
  uncommonOffalAndAnimals: freeze([
    "Bầu dục bò",
    "Bầu dục lợn",
    "Bì lợn",
    "Châu chấu",
    "Dạ dày bò",
    "Dạ dày lợn",
    "Dồi lợn",
    "Gân chân bò",
    "Giò thủ lợn",
    "Lòng gà (cả bộ)",
    "Lòng lợn (ruột già)",
    "Lòng lợn (ruột non)",
    "Lưỡi bò",
    "Lưỡi lợn",
    "Nhộng",
    "Phổi bò",
    "Phổi lợn",
    "Rạm (muối, đồ)",
    "Rạm tươi",
    "Rươi",
    "Thịt chó sấn",
    "Thịt chó vai",
    "Thịt hươu",
    "Thịt ngựa",
    "Tiết bò",
    "Tiết lợn luộc",
    "Tiết lợn sống",
    "Tủy xương bò",
    "Tủy xương lợn",
    "Óc bò",
    "Óc lợn",
    "Đuôi bò",
    "Đuôi lợn",
  ]),
  alcoholSweetsAndSnacks: freeze([
    "Bia",
    "Bánh bích quy",
    "Bánh chả",
    "Bánh con cá",
    "Bánh kem xốp",
    "Bánh khảo chay",
    "Bánh phồng tôm rán",
    "Bánh phồng tôm sống",
    "Bánh quẩy",
    "Bánh quế",
    "Bánh sô cô la",
    "Bánh thỏi sô cô la",
    "Bánh đậu xanh",
    "Bỏng ngô",
    "Chuối nước đường",
    "Coca cola",
    "Cô nhắc",
    "Cốc tai",
    "Dứa hộp",
    "Khoai tây lát chiên",
    "Kẹo Pastille",
    "Kẹo bơ cứng",
    "Kẹo cà phê",
    "Kẹo cam chanh",
    "Kẹo dứa mềm",
    "Kẹo dừa mềm",
    "Kẹo lạc",
    "Kẹo sô cô la",
    "Kẹo sữa",
    "Kẹo vừng viên",
    "Mận nước đường",
    "Mứt bí ngô",
    "Mứt cam có vỏ",
    "Mứt chuối",
    "Mứt dứa",
    "Mứt lạc",
    "Mứt đu đủ",
    "Nhãn nước đường",
    "Nước dứa hộp",
    "Rượu Whisky",
    "Rượu cam, chanh",
    "Rượu nếp",
    "Rượu vang trắng",
    "Rượu vang trắng ngọt",
    "Rượu vang đỏ",
    "Rượu trắng",
    "Vải nước đường",
  ]),
  condimentsAndRawIngredients: freeze([
    "Bột cá",
    "Bột dong lọc",
    "Bột gạo nếp",
    "Bột gạo tẻ",
    "Bột khoai lang",
    "Bột khoai riềng (bột đao)",
    "Bột khoai tây (lọc)",
    "Bột lạc",
    "Bột mì",
    "Bột ngô vàng",
    "Bột sắn",
    "Bột sắn dây",
    "Bột trứng",
    "Bột đậu tương rang chín",
    "Bột đậu tương đã loại béo",
    "Bột đậu xanh",
    "Cary bột",
    "Magi",
    "Mạch nha",
    "Mắm tép chua",
    "Mắm tôm loãng",
    "Mắm tôm đặc",
    "Men bia khô",
    "Men bia tươi",
    "Mỡ lợn muối",
    "Mỡ lợn nước",
    "Nước mắm cá",
    "Nước mắm cá (loại đặc biệt)",
    "Nước mắm cô",
    "Nước mắm loại I",
    "Nước mắm loại II",
    "Sốt mayonnaise",
    "Tương ngô",
    "Tương nếp",
    "Tương ớt",
    "Xì dầu",
    "Ớt khô bột",
    "Đường cát",
    "Đường kính",
  ]),
});

export const MEAL_PLAN_FOOD_CURATION_LABELS = Object.freeze(
  Object.values(MEAL_PLAN_FOOD_CURATION_GROUPS).flat(),
);

export const PROTECTED_VARIANT_LABELS = Object.freeze([
  "Quả bơ vỏ tím",
  "Quả bơ vỏ xanh",
]);
