export const EXPECTED_MUSCLE_GROUPS = Object.freeze([
  "Cardio / Tim mạch",
  "Chân",
  "Cơ bắp chân",
  "Cơ bụng / Eo",
  "Cơ cẳng tay",
  "Cơ cổ",
  "Cơ đùi trước / Đùi sau",
  "Cơ lưng",
  "Cơ ngực",
  "Cơ tay trước / Tay sau",
  "Cơ vai",
]);

export const EXERCISE_MANIFEST = Object.freeze([
  { name: "Burpee", muscleGroup: "Cardio / Tim mạch" },
  { name: "Mountain Climber", muscleGroup: "Cardio / Tim mạch" },
  { name: "Barbell Back Squat", muscleGroup: "Chân" },
  { name: "Bodyweight Standing Calf Raise", muscleGroup: "Cơ bắp chân" },
  { name: "Barbell Seated Calf Raise", muscleGroup: "Cơ bắp chân" },
  { name: "Crunch Floor", muscleGroup: "Cơ bụng / Eo" },
  { name: "Front Plank With Twist", muscleGroup: "Cơ bụng / Eo" },
  { name: "Band Wrist Curl", muscleGroup: "Cơ cẳng tay" },
  { name: "Barbell Reverse Wrist Curl", muscleGroup: "Cơ cẳng tay" },
  { name: "Neck Side Stretch", muscleGroup: "Cơ cổ" },
  { name: "Barbell Deadlift", muscleGroup: "Cơ đùi trước / Đùi sau" },
  { name: "Barbell Front Squat", muscleGroup: "Cơ đùi trước / Đùi sau" },
  { name: "Assisted Pull-up", muscleGroup: "Cơ lưng" },
  { name: "Alternate Lateral Pulldown", muscleGroup: "Cơ lưng" },
  { name: "Barbell Bench Press", muscleGroup: "Cơ ngực" },
  { name: "Archer Push Up", muscleGroup: "Cơ ngực" },
  { name: "Band Alternating Biceps Curl", muscleGroup: "Cơ tay trước / Tay sau" },
  {
    name: "Barbell Standing Overhead Triceps Extension",
    muscleGroup: "Cơ tay trước / Tay sau",
  },
  { name: "Barbell Shoulder Press", muscleGroup: "Cơ vai" },
  { name: "Cable Lateral Raise", muscleGroup: "Cơ vai" },
]);

export const FOOD_MANIFEST = Object.freeze([
  { label: "Ức gà", macroGroup: "protein" },
  { label: "Thịt bò nạc", macroGroup: "protein" },
  { label: "Cá hồi", macroGroup: "protein" },
  { label: "Cá ngừ", macroGroup: "protein" },
  { label: "Tôm biển", macroGroup: "protein" },
  { label: "Trứng gà", macroGroup: "protein" },
  { label: "Đậu phụ", macroGroup: "protein" },
  { label: "Cơm trắng", macroGroup: "carb" },
  { label: "Cơm gạo lứt", macroGroup: "carb" },
  { label: "Khoai lang", macroGroup: "carb" },
  { label: "Khoai tây", macroGroup: "carb" },
  { label: "Chuối", macroGroup: "carb" },
  { label: "Bún", macroGroup: "carb" },
  { label: "Phở", macroGroup: "carb" },
  { label: "Dầu olive", macroGroup: "fat" },
  { label: "Bơ trái", macroGroup: "fat" },
  { label: "Bơ đậu phộng", macroGroup: "fat" },
  { label: "Hạt hạnh nhân", macroGroup: "fat" },
  { label: "Hạt óc chó", macroGroup: "fat" },
  { label: "Hạt điều", macroGroup: "fat" },
]);
