// Mapping tên quốc gia (từ MealDB) → mã quốc gia 2 chữ cái
export const FLAG_MAP = {
  "Việt Nam": "vn",
  "Vietnamese": "vn",
  "British": "gb",
  "Anh": "gb",
  "American": "us",
  "Mỹ": "us",
  "United States": "us",
  "Chinese": "cn",
  "Trung Quốc": "cn",
  "Japanese": "jp",
  "Nhật Bản": "jp",
  "Thai": "th",
  "Thái Lan": "th",
  "Indian": "in",
  "India": "in",
  "Ấn Độ": "in",
  "French": "fr",
  "France": "fr",
  "Pháp": "fr",
  "Italian": "it",
  "Ý": "it",
  "Mexican": "mx",
  "Mexico": "mx",
  "Spanish": "es",
  "Tây Ban Nha": "es",
  "Greek": "gr",
  "Hy Lạp": "gr",
  "Turkish": "tr",
  "Thổ Nhĩ Kỳ": "tr",
  "Moroccan": "ma",
  "Ma-rốc": "ma",
  "Korean": "kr",
  "Hàn Quốc": "kr",
  "Filipino": "ph",
  "Philippines": "ph",
  "Malaysian": "my",
  "Malaysia": "my",
  "Russian": "ru",
  "Nga": "ru",
  "Polish": "pl",
  "Ba Lan": "pl",
  "Dutch": "nl",
  "Netherlands": "nl",
  "Hà Lan": "nl",
  "Ukrainian": "ua",
  "Ukraina": "ua",
  "Canadian": "ca",
  "Canada": "ca",
  "Irish": "ie",
  "Ireland": "ie",
  "Ai-len": "ie",
  "Jamaican": "jm",
  "Jamaica": "jm",
  "Egyptian": "eg",
  "Ai Cập": "eg",
  "Kenyan": "ke",
  "Kenya": "ke",
  "Portuguese": "pt",
  "Bồ Đào Nha": "pt",
  "Saudi Arabian": "sa",
  "Ả Rập Xê Út": "sa",
  "Croatian": "hr",
  "Croatia": "hr",
  "Tunisian": "tn",
  "Tunisia": "tn",
  "Norwegian": "no",
  "Norway": "no",
  "Na Uy": "no",
  "Australian": "au",
  "Úc": "au",
  "Argentine": "ar",
  "Argentina": "ar",
  "Algerian": "dz",
  "Algeria": "dz",
  "Venezuelan": "ve",
  "Venezuela": "ve",
  "Uruguayan": "uy",
  "Uruguay": "uy",
  "Syrian": "sy",
  "Syria": "sy",
  "Slovakian": "sk",
  "Slovakia": "sk",
};

export const getFlagUrl = (area) => {
  const code = FLAG_MAP[area];
  if (!code) return null;
  // Dùng FlagCDN (CDN chuyên dụng, mã nguồn mở, không sập) thay vì TheMealDB
  return `https://flagcdn.com/w80/${code}.png`;
};

// Hàm trả về emoji (do fallback TheMealDB image không dùng được trong <select>)
export const getFlagEmoji = (area) => {
  const emojiMap = {
    "Việt Nam": "🇻🇳",
    "Vietnamese": "🇻🇳",
    "British": "🇬🇧",
    "Anh": "🇬🇧",
    "American": "🇺🇸",
    "Mỹ": "🇺🇸",
    "United States": "🇺🇸",
    "Chinese": "🇨🇳",
    "Trung Quốc": "🇨🇳",
    "Japanese": "🇯🇵",
    "Nhật Bản": "🇯🇵",
    "Thai": "🇹🇭",
    "Thái Lan": "🇹🇭",
    "Indian": "🇮🇳",
    "India": "🇮🇳",
    "Ấn Độ": "🇮🇳",
    "French": "🇫🇷",
    "France": "🇫🇷",
    "Pháp": "🇫🇷",
    "Italian": "🇮🇹",
    "Ý": "🇮🇹",
    "Mexican": "🇲🇽",
    "Mexico": "🇲🇽",
    "Spanish": "🇪🇸",
    "Tây Ban Nha": "🇪🇸",
    "Greek": "🇬🇷",
    "Hy Lạp": "🇬🇷",
    "Turkish": "🇹🇷",
    "Thổ Nhĩ Kỳ": "🇹🇷",
    "Moroccan": "🇲🇦",
    "Ma-rốc": "🇲🇦",
    "Korean": "🇰🇷",
    "Hàn Quốc": "🇰🇷",
    "Filipino": "🇵🇭",
    "Philippines": "🇵🇭",
    "Malaysian": "🇲🇾",
    "Malaysia": "🇲🇾",
    "Russian": "🇷🇺",
    "Nga": "🇷🇺",
    "Polish": "🇵🇱",
    "Ba Lan": "🇵🇱",
    "Dutch": "🇳🇱",
    "Netherlands": "🇳🇱",
    "Hà Lan": "🇳🇱",
    "Ukrainian": "🇺🇦",
    "Ukraina": "🇺🇦",
    "Canadian": "🇨🇦",
    "Canada": "🇨🇦",
    "Irish": "🇮🇪",
    "Ireland": "🇮🇪",
    "Ai-len": "🇮🇪",
    "Jamaican": "🇯🇲",
    "Jamaica": "🇯🇲",
    "Egyptian": "🇪🇬",
    "Ai Cập": "🇪🇬",
    "Kenyan": "🇰🇪",
    "Kenya": "🇰🇪",
    "Portuguese": "🇵🇹",
    "Bồ Đào Nha": "🇵🇹",
    "Saudi Arabian": "🇸🇦",
    "Ả Rập Xê Út": "🇸🇦",
    "Croatian": "🇭🇷",
    "Croatia": "🇭🇷",
    "Tunisian": "🇹🇳",
    "Tunisia": "🇹🇳",
    "Norwegian": "🇳🇴",
    "Norway": "🇳🇴",
    "Na Uy": "🇳🇴",
    "Australian": "🇦🇺",
    "Úc": "🇦🇺",
    "Argentine": "🇦🇷",
    "Argentina": "🇦🇷",
    "Algerian": "🇩🇿",
    "Algeria": "🇩🇿",
    "Venezuelan": "🇻🇪",
    "Venezuela": "🇻🇪",
    "Uruguayan": "🇺🇾",
    "Uruguay": "🇺🇾",
    "Syrian": "🇸🇾",
    "Syria": "🇸🇾",
    "Slovakian": "🇸🇰",
    "Slovakia": "🇸🇰",
  };
  return emojiMap[area] || "🌎";
};

/**
 * Smart pagination: 1 2 3 ... 30 31 32 ... 63
 */
export const getPageNumbers = (current, total) => {
  if (total <= 7) return Array.from({ length: total }, (_, i) => i + 1);

  const pages = [1];

  if (current > 3) pages.push("...");

  const start = Math.max(2, current - 1);
  const end = Math.min(total - 1, current + 1);
  for (let i = start; i <= end; i++) pages.push(i);

  if (current < total - 2) pages.push("...");

  pages.push(total);

  return pages;
};
