const ingredient = (name, ...aliases) => ({ name, aliases });

export const GLOBAL_SYNTHETIC_PROXY_CASES = [
  {
    caseId: "margherita-pizza-shared",
    imageFile: "margherita-pizza-shared.png",
    mealAliases: [
      "pizza margherita",
      "margherita pizza",
      "pizza phô mai cà chua",
    ],
    expectedScenario: "shared_meal",
    ingredientGroups: [
      ingredient("đế pizza", "đế pizza", "đế bánh pizza", "vỏ bánh", "pizza crust", "dough"),
      ingredient("sốt cà chua", "sốt cà chua", "cà chua", "tomato sauce"),
      ingredient("phô mai mozzarella", "phô mai", "mozzarella", "cheese"),
      ingredient("húng quế", "húng quế", "lá húng", "basil"),
    ],
  },
  {
    caseId: "steak-frites",
    imageFile: "steak-frites.png",
    mealAliases: [
      "bít tết và khoai tây chiên",
      "bò bít tết và khoai tây chiên",
      "bít tết bò kèm khoai tây chiên",
      "bít tết bò",
      "steak frites",
      "steak and fries",
    ],
    expectedScenario: "plated_meal",
    ingredientGroups: [
      ingredient("bít tết", "bít tết", "thịt bò", "beef steak", "steak"),
      ingredient("khoai tây chiên", "khoai tây chiên", "french fries", "fries"),
      ingredient("sốt tiêu", "sốt tiêu", "sốt kem tiêu", "peppercorn sauce"),
      ingredient("rau xà lách", "xà lách", "rau trộn", "salad", "greens"),
    ],
  },
  {
    caseId: "spaghetti-carbonara",
    imageFile: "spaghetti-carbonara.png",
    mealAliases: [
      "mì ý carbonara",
      "mỳ ý carbonara",
      "spaghetti carbonara",
      "pasta carbonara",
    ],
    expectedScenario: "plated_meal",
    ingredientGroups: [
      ingredient("mì spaghetti", "mì ý", "mỳ ý", "spaghetti", "pasta"),
      ingredient("thịt muối", "thịt muối", "thịt xông khói", "pancetta", "bacon"),
      ingredient("phô mai", "phô mai", "parmesan", "pecorino", "cheese"),
      ingredient("trứng", "trứng", "sốt trứng", "egg", "egg sauce"),
      ingredient("tiêu đen", "tiêu", "tiêu đen", "black pepper"),
    ],
  },
  {
    caseId: "croissant-pain-au-chocolat",
    imageFile: "croissant-pain-au-chocolat.png",
    mealAliases: [
      "croissant và pain au chocolat",
      "bánh sừng bò và pain au chocolat",
      "croissant and pain au chocolat",
      "bánh sừng bò và bánh sô cô la",
    ],
    expectedScenario: "dessert",
    ingredientGroups: [
      ingredient("croissant", "croissant", "bánh sừng bò"),
      ingredient("pain au chocolat", "pain au chocolat", "bánh sô cô la", "chocolate pastry"),
      ingredient("nhân sô cô la", "sô cô la", "chocolate", "chocolate filling"),
    ],
  },
  {
    caseId: "tiramisu",
    imageFile: "tiramisu.png",
    mealAliases: ["tiramisu", "bánh tiramisu", "italian tiramisu"],
    expectedScenario: "dessert",
    ingredientGroups: [
      ingredient("lớp kem", "kem", "mascarpone", "cream"),
      ingredient(
        "bánh ladyfinger",
        "ladyfinger",
        "ladyfingers",
        "bánh sampa",
        "bánh quy",
        "sponge cake",
      ),
      ingredient("bột ca cao", "ca cao", "cacao", "cocoa"),
    ],
  },
  {
    caseId: "sushi-assortment",
    imageFile: "sushi-assortment.png",
    mealAliases: ["sushi tổng hợp", "sushi thập cẩm", "assorted sushi", "sushi"],
    expectedScenario: "plated_meal",
    ingredientGroups: [
      ingredient("cơm sushi", "cơm sushi", "cơm", "sushi rice", "rice"),
      ingredient("cá hồi", "cá hồi", "salmon"),
      ingredient("cá ngừ", "cá ngừ", "tuna"),
      ingredient("tôm", "tôm", "shrimp", "prawn"),
      ingredient("dưa leo và bơ", "dưa leo", "dưa chuột", "bơ", "cucumber", "avocado"),
      ingredient("rong biển", "rong biển", "nori", "seaweed"),
      ingredient("nước tương", "nước tương", "xì dầu", "soy sauce"),
    ],
  },
  {
    caseId: "bibimbap",
    imageFile: "bibimbap.png",
    mealAliases: ["bibimbap", "cơm trộn hàn quốc", "korean mixed rice"],
    expectedScenario: "plated_meal",
    ingredientGroups: [
      ingredient("cơm", "cơm", "rice"),
      ingredient("thịt bò", "thịt bò", "bò", "beef"),
      ingredient("trứng", "trứng", "trứng ốp la", "egg"),
      ingredient("rau chân vịt", "rau chân vịt", "cải bó xôi", "spinach"),
      ingredient("cà rốt", "cà rốt", "carrot"),
      ingredient("giá đỗ", "giá", "giá đỗ", "bean sprouts"),
      ingredient("bí ngòi", "bí ngòi", "zucchini"),
      ingredient("nấm", "nấm", "mushroom"),
      ingredient("tương ớt gochujang", "gochujang", "tương ớt", "chili paste"),
    ],
  },
  {
    caseId: "brown-sugar-bubble-tea",
    imageFile: "brown-sugar-bubble-tea.png",
    mealAliases: [
      "trà sữa trân châu đường đen",
      "trà sữa đường đen",
      "brown sugar bubble tea",
      "brown sugar boba",
    ],
    expectedScenario: "drink",
    ingredientGroups: [
      ingredient("trà sữa", "trà sữa", "milk tea"),
      ingredient("trân châu", "trân châu", "boba", "tapioca pearls"),
      ingredient("siro đường đen", "đường đen", "siro đường", "brown sugar syrup"),
    ],
  },
];
