const ingredient = (name, ...aliases) => ({ name, aliases });

export const VIETNAMESE_SYNTHETIC_PROXY_CASES = [
  {
    caseId: "pho-bo",
    imageFile: "pho-bo.png",
    mealAliases: ["phở bò", "pho bo", "beef pho"],
    ingredientGroups: [
      ingredient("bánh phở", "bánh phở", "phở", "rice noodles"),
      ingredient("thịt bò", "thịt bò", "bò", "beef"),
      ingredient("hành", "hành lá", "hành tây", "scallion", "onion"),
      ingredient("rau thơm", "rau thơm", "ngò", "herbs", "cilantro"),
      ingredient("giá", "giá", "bean sprouts"),
      ingredient("chanh", "chanh", "lime"),
    ],
  },
  {
    caseId: "com-tam-suon-bi-cha",
    imageFile: "com-tam-suon-bi-cha.png",
    mealAliases: [
      "cơm tấm sườn bì chả",
      "cơm tấm",
      "com tam",
      "broken rice",
    ],
    ingredientGroups: [
      ingredient("cơm tấm", "cơm", "cơm tấm", "broken rice", "rice"),
      ingredient("sườn nướng", "sườn", "thịt nướng", "pork chop"),
      ingredient("bì", "bì", "da heo", "shredded pork skin"),
      ingredient("chả trứng", "chả", "chả trứng", "egg meatloaf"),
      ingredient("dưa leo", "dưa leo", "dưa chuột", "cucumber"),
      ingredient("cà chua", "cà chua", "tomato"),
      ingredient("đồ chua", "đồ chua", "cà rốt", "pickles", "pickled vegetables"),
      ingredient("nước mắm", "nước mắm", "fish sauce"),
    ],
  },
  {
    caseId: "bun-cha",
    imageFile: "bun-cha.png",
    mealAliases: ["bún chả", "bun cha", "grilled pork with noodles"],
    ingredientGroups: [
      ingredient("bún", "bún", "rice vermicelli", "rice noodles"),
      ingredient("chả nướng", "chả", "thịt viên", "pork patty"),
      ingredient("thịt ba chỉ", "ba chỉ", "thịt heo", "pork belly", "pork"),
      ingredient("rau sống", "rau sống", "rau thơm", "herbs", "lettuce"),
      ingredient("đồ chua", "đồ chua", "cà rốt", "pickles", "carrot"),
      ingredient("nước mắm", "nước mắm", "nước chấm", "fish sauce"),
    ],
  },
  {
    caseId: "banh-mi-thit",
    imageFile: "banh-mi-thit.png",
    mealAliases: ["bánh mì thịt", "bánh mì", "banh mi", "vietnamese sandwich"],
    ingredientGroups: [
      ingredient("bánh mì", "bánh mì", "baguette", "bread"),
      ingredient("thịt heo", "thịt heo", "thịt", "pork"),
      ingredient("pa-tê", "pa tê", "pate", "pâté"),
      ingredient("dưa leo", "dưa leo", "dưa chuột", "cucumber"),
      ingredient("đồ chua", "đồ chua", "cà rốt", "pickles", "pickled vegetables"),
      ingredient("rau mùi", "ngò", "rau mùi", "cilantro", "coriander"),
      ingredient("ớt", "ớt", "chili"),
    ],
  },
  {
    caseId: "bun-bo-hue",
    imageFile: "bun-bo-hue.png",
    mealAliases: ["bún bò huế", "bun bo hue", "hue beef noodle soup"],
    ingredientGroups: [
      ingredient("bún", "bún", "rice noodles", "rice vermicelli"),
      ingredient("thịt bò", "thịt bò", "bò", "beef"),
      ingredient("giò heo", "giò heo", "chân giò", "pork hock", "pork knuckle"),
      ingredient("chả", "chả", "chả lụa", "pork sausage"),
      ingredient("rau và giá", "rau", "rau thơm", "giá", "herbs", "bean sprouts"),
    ],
  },
  {
    caseId: "banh-xeo",
    imageFile: "banh-xeo.png",
    mealAliases: ["bánh xèo", "banh xeo", "vietnamese savory crepe"],
    ingredientGroups: [
      ingredient("vỏ bánh xèo", "bánh xèo", "bột gạo", "rice crepe", "crepe"),
      ingredient("tôm", "tôm", "shrimp", "prawn"),
      ingredient("thịt heo", "thịt heo", "thịt", "pork"),
      ingredient("giá", "giá", "bean sprouts"),
      ingredient("rau sống", "rau sống", "rau thơm", "greens", "herbs", "lettuce"),
      ingredient("nước mắm", "nước mắm", "nước chấm", "fish sauce"),
    ],
  },
  {
    caseId: "goi-cuon",
    imageFile: "goi-cuon.png",
    mealAliases: ["gỏi cuốn", "goi cuon", "fresh spring rolls", "summer rolls"],
    ingredientGroups: [
      ingredient("bánh tráng", "bánh tráng", "rice paper"),
      ingredient("tôm", "tôm", "shrimp", "prawn"),
      ingredient("thịt heo", "thịt heo", "thịt", "pork"),
      ingredient("bún", "bún", "rice vermicelli", "rice noodles"),
      ingredient("rau", "rau", "xà lách", "lettuce", "herbs"),
      ingredient("tương đậu phộng", "tương", "đậu phộng", "peanut sauce", "hoisin"),
    ],
  },
  {
    caseId: "ca-kho-to",
    imageFile: "ca-kho-to.png",
    mealAliases: ["cá kho tộ", "ca kho to", "braised fish", "caramelized fish"],
    ingredientGroups: [
      ingredient("cá", "cá", "cá trê", "fish", "catfish"),
      ingredient("nước kho", "nước kho", "nước màu", "caramel sauce", "braising sauce"),
      ingredient("cơm", "cơm", "rice"),
      ingredient("rau muống", "rau muống", "morning glory", "water spinach"),
      ingredient("hành và tiêu", "hành", "tiêu", "scallion", "pepper"),
    ],
  },
];
